# App
spring.application.name=urlshortener
server.port=${PORT:8080}

# PostgreSQL
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Redis — sirf URL kaafi hai Railway pe
spring.data.redis.url=${REDIS_URL}

# JWT
app.jwt.secret=${JWT_SECRET:mySecretKey12345678901234567890123456789012}
app.jwt.expiration=86400000

# Base URL
app.base-url=${BASE_URL:http://localhost:8080}
app.rate-limit.max-requests=${RATE_LIMIT:10}

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_URL:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.group-id=analytics-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.auto-offset-reset=earliest

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# Connection Pool
server.tomcat.threads.max=200
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=3000